// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Configuration for Firebase
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXwDIzKAEJDS6fRO1D6F2h4uxPMMjnl1w',
    appId: '1:831202062037:android:9a29d7d450f7706d157c5c',
    messagingSenderId: '831202062037',
    projectId: 'itpm-ac334',
    storageBucket: 'itpm-ac334.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXwDIzKAEJDS6fRO1D6F2h4uxPMMjnl1w',
    appId: '1:831202062037:ios:9a29d7d450f7706d157c5c',
    messagingSenderId: '831202062037',
    projectId: 'itpm-ac334',
    storageBucket: 'itpm-ac334.firebasestorage.app',
    iosBundleId: 'com.example.peerBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXwDIzKAEJDS6fRO1D6F2h4uxPMMjnl1w',
    appId: '1:831202062037:windows:9a29d7d450f7706d157c5c',
    messagingSenderId: '831202062037',
    projectId: 'itpm-ac334',
    storageBucket: 'itpm-ac334.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDXwDIzKAEJDS6fRO1D6F2h4uxPMMjnl1w',
    appId: '1:831202062037:linux:9a29d7d450f7706d157c5c',
    messagingSenderId: '831202062037',
    projectId: 'itpm-ac334',
    storageBucket: 'itpm-ac334.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXwDIzKAEJDS6fRO1D6F2h4uxPMMjnl1w',
    appId: '1:831202062037:web:9a29d7d450f7706d157c5c',
    messagingSenderId: '831202062037',
    projectId: 'itpm-ac334',
    storageBucket: 'itpm-ac334.firebasestorage.app',
  );
}
